name = "Solvers"
uuid = "54bf0e5c-3360-4b1b-8076-d7fd7d08b4dc"
authors = ["Alexandre Magueresse <alexandre.magueresse@monash.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
